### ISSUE TITLE
How does this run irix?

### ISSUE THREAD

**Issue by psxpetey** [irixxxx/qemu#2]
Looking to run irix 5.3-6.5 on qemu is that what this software does?

**Comment by irixxxx** [comment]
No, it doesn't allow to run the IRIX system. It allows to run IRIX applications on top of a Linux system, using the Linux system call layer as a high-level emulation for IRIX system calls.
t's not the same as emulating the full system, since linux system call behaviour isn't always the same as IRIX's. Some baroque properties of IRIX cannot be emulated by Linux, and some of the standard IRIX system hardware (e.g. the graphics hardware) isn't available.

**Comment by psxpetey** [comment]
Thanks much appreciated
